version: '3.8'

networks:
  default:
    name: ultra-last-next-net

services:
  nginx:
    container_name: ultra-last-next-nginx
    image: 'nginx:stable-alpine'
    ports:
      - '40003:80'
    restart: unless-stopped
    volumes:
      - ./server:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    container_name: ultra-last-next-php
    restart: unless-stopped
    build:
      context: ./server
    volumes:
      - ./server:/var/www/html:delegated
